### ISSUE TITLE
http://127.0.0.1/cms/admin/posts.php (un identified array index)

### ISSUE THREAD

**Issue by CuriousEmmanuel** [CuriousEmmanuel/blogging_site_with_cms#1]
![error message](https://github.com/CuriousEmmanuel/c_ms/assets/107352649/99fd18e7-c8a4-48b0-a44c-93bf7ffe6b42)

**Comment by imaarov** [comment]
Hi,
after you check for the submit button you should also check for all of your inputs(use empty(), isset() too see if the inputs are empty or not) to check the content of them, or make the inputs required,
the code of the add post is also not linked in the admin panel so you may have changes that you don't publish

**Comment by CuriousEmmanuel** [comment]
The issue is in line 9 and 10 on cms/admin/posts.php
So should I check for example isset($_POST['image']
Or  isset($_FILES['image']

**Comment by imaarov** [comment]
i see , the enctype set is wrong `enctype="multipert/form-data"`
it should be `enctype="multipart/form-data"`
https://github.com/CuriousEmmanuel/c_ms/blob/cbf66de0b354d3f4b24d1889a38f2771dc85af02/cms/admin/includes/add_post.php#L23

**Comment by CuriousEmmanuel** [comment]
And it just worked like how did you find that typo out
I couldn't have find it thank you so much #imaarov
