### ISSUE TITLE
after deleting and uploading other files now buttons doesnt work and some links links in the index page so I csnt login because the form has an issue too

### ISSUE THREAD

**Issue by CuriousEmmanuel** [CuriousEmmanuel/blogging_site_with_cms#5]
post title
postaouthor 
and read more button are supposed when clicked to take you to that specific post ad display the post content in full plus add comment form

**Comment by CuriousEmmanuel** [comment]
and I don't know should I create a branch for pull requests or what?

**Comment by CuriousHack** [comment]
I'd like to participate in this project, the index page is actually  displaying the title of the blog and the author, you just need to make the title and the author name to be different in the database

**Comment by CuriousEmmanuel** [comment]
> I'd like to participate in this project, the index page is actually  displaying the title of the blog and the author, you just need to make the title and the author name to be different in the database

Yes You can participate and it will be great 
Fork the repo and play with it it's open you can use it as a framework to make something new for yourself

**Comment by CuriousEmmanuel** [comment]
I found out my server had an issue that's why the links weren't redirecting
