### ISSUE TITLE
post_comment_count error

### ISSUE THREAD

**Issue by CuriousHack** [CuriousEmmanuel/blogging_site_with_cms#6]
Update the 'Read More' button so that it takes the visitor to the single blog page of the certain blog post.

**Comment by CuriousEmmanuel** [comment]
yeah ok thats necesary

**Comment by CuriousHack** [comment]
please always create an issue whenever you need help or need to fix a bug so others can know what to do

**Comment by CuriousEmmanuel** [comment]
> please always create an issue whenever you need help or need to fix a bug so others can know what to do

yeah I always will in fact check that project its a mile away even though there is an issue with adding post (add_post.php)

**Comment by CuriousEmmanuel** [comment]
The error is solved and it just created another 
Now the comment_count is not counting the number of comments

<<<<<<<<<admin/includes/add_post.php>>>>>>>>>>>>>>>>>>>>


if (isset($_POST['create_post'])){

$post_title = $_POST['title'];
$post_category_id = $_POST['post_category'];
$post_author = $_POST['post_author'];
$post_status= $_POST['post_status'];

$post_image = $_FILES['image']['name'];
$post_image_temp = $_FILES['image']['tmp_name'];//sending files to a temporary location on the server

$post_tags= $_POST['post_tags'];
$post_date= date('d-m-y'); //sendin the DATE WITH A FUNCTION IN THAT FORMAT
$post_content = $_POST['post_content'];
// $post_comment_count = 1;

//function to move images from a temporary location to a folder outside admin 

move_uploaded_file($post_image_temp, "../images/$post_image" );


// one field more tha the other (post comment count) find its value or delete it which will cause another error


$query = " INSERT INTO posts(post_category_id,post_title,post_author,post_date,post_image,post_content,post_tags, post_comment_count,post_status) " ;

$query.= " VALUES ({$post_category_id },'{$post_title}','{$post_author}',now(),'{$post_image}','{$post_content }','{$post_tags}',' ','{$post_status}') " ;
//////////////////////////////////////////////////////////// in btwn post_tags and post_status I put a blank string to bypass the error and it is the reason why it can not count the number of comments in that specific post/////////////////////////////////////////////////////////////////

$add_post_query = mysqli_query($connection,$query);

**Comment by CuriousHack** [comment]
The `$post_comment_count` by default should be `zero` as the post is just 
being created and when a visitor added a comment, the count should be updated by adding `1` to it for every new comment

**Comment by CuriousEmmanuel** [comment]
> The `$post_comment_count` by default should be `zero` as the post is just being created and when a visitor added a comment, the count should be updated by adding `1` to it for every new comment

and should it be included in the posts query since we have that field for comment cont also in posts 
and if ignored it results to an error

**Comment by CuriousHack** [comment]
it depends on how the database is structured, it the field can be `empty` in the database or `0` as the default, then we can escape it in the add_post field

**Comment by CuriousEmmanuel** [comment]
I found out the best way instead of keeping track of posts which require allot of code we can just count the number of rows in the comments table related to that specific comment_post_id
